# Generated by Django 6.0 on 2026-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
