# Generated by Django 6.0.1 on 2026-01-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_paid',
            field=models.BooleanField(default=False),
        ),
    ]
