# Generated by Django 6.0.1 on 2026-01-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
