# Generated by Django 6.0.1 on 2026-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_remove_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
